Visitor can see the articles according to their categories
CraftAcademy/news-on-rails-client-2020 pull request #6
Opened 2020-08-10 16:29 UTC by Odeane

## [PT board URL]( https://www.pivotaltracker.com/story/show/173920523 )
### User Story
```
As a visitor 
in order to get relevant news
I would like to see the articles in categories
```
## Changes proposed in this pull request:
* User can now view articles based on their category

## What I have learned working on this feature:
* We learned how to use react router

## Packages added
- axios
- react-router-dom
## Screenshots (Client)
![Screenshot 2020-08-10 at 18 27 19](https://user-images.githubusercontent.com/64922951/89806378-3b222880-db37-11ea-9195-1fdb70b76b15.png)

![Screenshot 2020-08-10 at 18 27 45](https://user-images.githubusercontent.com/64922951/89806399-4412fa00-db37-11ea-8f88-79bd6d108301.png)

2020-08-10 19:39 UTC, viktorsommar approved these changes
Left some comments about the message about the categories conditional

2020-08-10 19:39 UTC, viktorsommar commented on src/Components/Pages/EconomyPage.jsx
> +            return 'Unable to show categories'
Shouldn't this say "Unable to show articles"? Or "No articles were found"?

2020-08-10 19:39 UTC, viktorsommar commented on src/Components/Pages/LifestylePage.jsx
> +              return 'Unable to show categories'
Shouldn't this say "Unable to show articles"? Or "No articles were found"?

2020-08-10 19:39 UTC, viktorsommar commented on src/Components/Pages/SportsPage.jsx
> +              return 'Unable to show categories'
Shouldn't this say "Unable to show articles"? Or "No articles were found"?

2020-08-11 07:18 UTC, Felix-Willborg approved these changes

2020-08-11 13:30 UTC, oliverochman requested changes

2020-08-11 13:30 UTC, oliverochman commented on src/Components/Articles.jsx
> +    console.log(response)
plz remove console log

2020-08-11 13:32 UTC, Odeane commented on src/Components/Articles.jsx
> +    console.log(response)
resolved

2020-08-11 13:35 UTC, emtalen commented on src/Components/Articles.jsx
> +        }
I would try this request while running the backend to make sure it is working, if you haven't done that. To make sure you don't get the params keyword twice in the request

2020-08-11 13:55 UTC, merged