Subscriber must logged in to view  premium content
CraftAcademy/news-on-rails-client-2020 pull request #7
Opened 2020-08-17 18:13 UTC by Cma-B

## [PT board URL](https://www.pivotaltracker.com/story/show/173930344 )
### User Story
```
As a Subscriber
In order to access the premium content
I would like to log in
```
## Changes proposed in this pull request:
*  adds restriction in displaying articles according to the different role, subscriber and registered user
* adds login button and login form
## What I have learned working on this feature:
* working with redux
*working with j-tockAuth
## Packages/Gems added
- j-tockAuth
- redux-react

2020-08-17 18:40 UTC, viktorsommar approved these changes

2020-08-17 18:42 UTC, Alex-Bellamy approved these changes

2020-08-18 07:36 UTC, oliverochman requested changes

2020-08-18 07:36 UTC, oliverochman commented on src/components/Articles.jsx
> +    //whether the user login or not
please remove commented out code

2020-08-18 08:53 UTC, emtalen approved these changes

2020-08-18 08:53 UTC, merged